blank_issues_enabled: false
contact_links:
  - name: ❓ General Question / Discussion
    url: https://github.com/amyavari/persian-faker-php/discussions
    about: "For general discussions, questions, or help, use GitHub Discussions."
