name: "✨ Feature Request"
description: "Suggest a new feature or improvement."
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "## 🌟 Feature Request\nDescribe your suggestion."

  - type: input
    id: title
    attributes:
      label: "Feature Title"
      placeholder: "A short and clear name for the feature."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Explain why this feature is needed."
      placeholder: "It would be helpful because..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: "Use Case"
      description: "Provide a real-world scenario for this feature."
      placeholder: "A user needs this feature when..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Have you considered other approaches?"
      placeholder: "Instead of this feature, I could..."
    validations:
      required: false
